### ISSUE TITLE
Parse error: Failed to construct DelphiFile (line 5883:0 missing FORWARD at 'var')

### ISSUE THREAD

**Issue by Scharrels** [integrated-application-development/sonar-delphi#269] opened 2024-07-15 14:02 UTC
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.7.0

### SonarQube version

10.5.1

### Issue description

The following error occurs on multiple files in our project. Luckily, one of the files is FastMM5, making it possible to report this bug without sharing our own code. The following file causes the error:

https://github.com/pleriche/FastMM5/blob/version_505/FastMM5.pas

This causes the sonar-delphi to crash with the following stacktrace:

```
14:44:25.820 ERROR Error while processing <projectpath>\fastmm\FastMM5.pas

au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (line 5883:0 missing FORWARD at 'var')
	at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:161)
	at au.com.integradev.delphi.file.DelphiFile.from(DelphiFile.java:136)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.process(SymbolTableBuilder.java:284)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.processImportsWithInlineRoutines(SymbolTableBuilder.java:371)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.process(SymbolTableBuilder.java:293)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.indexUnit(SymbolTableBuilder.java:396)
	at au.com.integradev.delphi.symbol.SymbolTableBuilder.build(SymbolTableBuilder.java:477)
	at au.com.integradev.delphi.DelphiSensor.executeOnFiles(DelphiSensor.java:119)
	at au.com.integradev.delphi.DelphiSensor.execute(DelphiSensor.java:83)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:204)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:200)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:173)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringScannerContainer.doAfterStart(SpringScannerContainer.java:351)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:138)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:226)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:205)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:71)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:65)
	at org.sonarsource.scanner.lib.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:41)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.lib.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:62)
	at jdk.proxy3/jdk.proxy3.$Proxy2.execute(Unknown Source)
	at org.sonarsource.scanner.lib.InProcessScannerEngineFacade.doAnalyze(InProcessScannerEngineFacade.java:39)
	at org.sonarsource.scanner.lib.ScannerEngineFacade.analyze(ScannerEngineFacade.java:61)
	at org.sonarsource.scanner.cli.Main.analyze(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:63)
Caused by: au.com.integradev.delphi.antlr.DelphiParser$ParserException: line 5883:0 missing FORWARD at 'var'
	at au.com.integradev.delphi.antlr.DelphiParser.reportError(DelphiParser.java:387)
	at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:613)
	at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:115)
	at au.com.integradev.delphi.antlr.DelphiParser.forwardDirectiveSection(DelphiParser.java:32532)
	at au.com.integradev.delphi.antlr.DelphiParser.forwardRoutineHeading(DelphiParser.java:16915)
	at au.com.integradev.delphi.antlr.DelphiParser.forwardRoutine(DelphiParser.java:16097)
	at au.com.integradev.delphi.antlr.DelphiParser.routineImplementation(DelphiParser.java:15863)
	at au.com.integradev.delphi.antlr.DelphiParser.declSection(DelphiParser.java:3480)
	at au.com.integradev.delphi.antlr.DelphiParser.unitImplementation(DelphiParser.java:2002)
	at au.com.integradev.delphi.antlr.DelphiParser.unit(DelphiParser.java:1618)
	at au.com.integradev.delphi.antlr.DelphiParser.file(DelphiParser.java:524)
	at au.com.integradev.delphi.file.DelphiFile.createAST(DelphiFile.java:196)
	at au.com.integradev.delphi.file.DelphiFile.setupFile(DelphiFile.java:149)
	... 38 common frames omitted
Caused by: org.antlr.runtime.MissingTokenException: null
	at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:612)
	... 49 common frames omitted
```

### Steps to reproduce

The easiest way to reproduce this is to do a DelphiLint analysis on the following file:

https://github.com/pleriche/FastMM5/blob/version_505/FastMM5.pas

This shows the same error as sonar-delphi.

### Minimal Delphi code exhibiting the issue

https://github.com/pleriche/FastMM5/blob/version_505/FastMM5.pas

**Comment by zaneduffield** [comment] 2024-07-15 23:48
Hi @Scharrels, thanks for reporting this issue.
I was able to reproduce it after setting `sonar.delphi.toolchain` to `DCC64`.

I reduced the problem to this minimal example
```delphi
procedure Foo;
{$if False}
asm
{$else}
begin
  var x := @Foo;
{$endif}
end;
```

What's happening here is the lexer is switching into ASM mode before the conditional directive processor has eliminated the `asm` branch, and the ASM label token generated make no sense to the grammar. It's an issue related to #261.

**Comment by Cirras** [comment] 2024-07-16 00:11
As @zaneduffield noted, this would be fixed with #261.

However, I think it's a bad enough problem to warrant a medium-term hack.
It might be as simple as popping the `asm` mode in the parser when we encounter a `begin` token.

**Closed** 2024-08-07 01:26 UTC
Labels: bug

**Comment by fchandan** [comment] 2025-10-17 23:09
Hi, I faced a similar issue as this one but on DCC32. Is there a fix for DCC32 as we use the Delphi 2007 version and we see the same issue when running sonarcube scanner as we have to set sonar.delphi.toolchain to DCC32. Is there any fix for this issue? Your assistance would be really helpful here.

**Comment by cirras** [comment] 2025-10-17 23:35
> Hi, I faced a similar issue as this one but on DCC32. Is there a fix for DCC32 as we use the Delphi 2007 version and we see the same issue when running sonarcube scanner as we have to set sonar.delphi.toolchain to DCC32. Is there any fix for this issue? Your assistance would be really helpful here.

Hi @fchandan,
 
Please raise a new issue with a minimal reproducible case for us to look at.

This issue was a parsing problem around conditional `asm` and `begin` blocks and only related to the toolchain because of a different conditional branch being active in the source file.

The root issue you're encountering may be something entirely different, so we'll really need a minimal source code example that triggers the error.

**Comment by fchandan** [comment] 2025-10-23 16:48
Hi @cirras, 

I tried to reproduce this issue, I do not believe it is because of the conditional asm and begin blocks. However, I could not reproduce it to a smaller subset of code. We do have certain Japanese comments in place, and the length of the function is over 1000 lines which could be potential problem. 

May I know what could be the probable reasons that this error could be encountered? Or if you have any suggestions on this issue.

**Comment by cirras** [comment] 2025-10-26 14:28
> Hi [@cirras](https://github.com/cirras),
> 
> I tried to reproduce this issue, I do not believe it is because of the conditional asm and begin blocks. However, I could not reproduce it to a smaller subset of code. We do have certain Japanese comments in place, and the length of the function is over 1000 lines which could be potential problem.
> 
> May I know what could be the probable reasons that this error could be encountered? Or if you have any suggestions on this issue.

Hi @fchandan,

The easiest way to isolate the problem in your case would be to incrementally remove code from the function until the error disappears from your scan.

From there, you should be able to figure out which part of the function is currently incompatible with our parser and raise an issue with a minimal example. 

Alternatively, you can anonymize the function (identifier names, comments, strings, etc.) and post the entire thing to a new issue. If you do this, please run a scan to make sure that the anonymized function still triggers the same error.
